//
//  hypTreeMap.h
//
//  Authors: Nicolae Mihalache, François Vigneron
//
//  Please cite the references below if you use or distribute this software.
//
//  • [1] N. Mihalache & F. Vigneron. How to split a tera-polynomial. 2021.
//  • [2] N. Mihalache & F. Vigneron. How to compute the coefficients of holomorphic maps. 2021.
//
//  Copyright 2019 - 2021 Univ. Paris-Est Créteil, Univ. de Reims Champagne-Ardenne.
//  This software is released under the Lesser GNU Public Licence v3.0 (LGPL3)
//

/**
  \file hypTreeMap.h
  \brief This app computes the tree map of the hyperbolic centers of a given period.
 
  It uses the files generated by hypCountMain() that contain all hyperbolic centers without repetitions. Several maps
  with different resolutions (power of two or the max level of the tree) can be produced in one pass. As the @ref nset files
  produced by hypCountMain() have an MD5 checksum included, this is also a test that those files are correctly written to
  the storage medium.
 
  Each map generated by this app contains an MD5 checksum and is reloaded after it has been saved. If no error is reported,
  this is a guarantee that the file is not corrupted and the measure (or planar histogram) of the hyperbolic centers can be published.
*/

#define HYP_TREE_GLOBAL_LEV  20
#define HYP_TREE_MIN_LEV     22
#define HYP_TREE_MAX_LEV     30
#define HYP_TREE_LEV_STEP     2
#define HYP_TREE_GROUP        8

#ifndef hypTreeMap_h
#define hypTreeMap_h

/// @brief Interprets the command line arguments, and produces the requested tree maps of the results.
///
/// @param argc the number of command line arguments
/// @param argv the command line arguments
///
/// @return @c 0 if successfull, @c 1 otherwise
int hyp_tree_main(int argc, const char * argv[]);

#endif /* hypTreeMap_h */
